/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CustomCheckboxGroup: typeof import('./src/components/input/CustomCheckboxGroup.vue')['default']
    CustomInputGroup: typeof import('./src/components/input/CustomInputGroup.vue')['default']
    CustomInputNoLabel: typeof import('./src/components/input/CustomInputNoLabel.vue')['default']
    CustomMultiSelectGroup: typeof import('./src/components/input/CustomMultiSelectGroup.vue')['default']
    CustomPasswordInputGroup: typeof import('./src/components/input/CustomPasswordInputGroup.vue')['default']
    CustomRadioGroup: typeof import('./src/components/input/CustomRadioGroup.vue')['default']
    CustomSelectGroup: typeof import('./src/components/input/CustomSelectGroup.vue')['default']
    CustomSelectNoLabel: typeof import('./src/components/input/CustomSelectNoLabel.vue')['default']
    CustomTextareaGroup: typeof import('./src/components/input/CustomTextareaGroup.vue')['default']
    CustomToggleSwitchGroup: typeof import('./src/components/input/CustomToggleSwitchGroup.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToastComponent: typeof import('./src/components/ToastComponent.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
